In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [11]:
X,y=load_breast_cancer(return_X_y=True)


In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [25]:
X_test

array([[1.247e+01, 1.860e+01, 8.109e+01, ..., 1.015e-01, 3.014e-01,
        8.750e-02],
       [1.894e+01, 2.131e+01, 1.236e+02, ..., 1.789e-01, 2.551e-01,
        6.589e-02],
       [1.546e+01, 1.948e+01, 1.017e+02, ..., 1.514e-01, 2.837e-01,
        8.019e-02],
       ...,
       [1.152e+01, 1.493e+01, 7.387e+01, ..., 9.608e-02, 2.664e-01,
        7.809e-02],
       [1.422e+01, 2.785e+01, 9.255e+01, ..., 8.219e-02, 1.890e-01,
        7.796e-02],
       [2.073e+01, 3.112e+01, 1.357e+02, ..., 1.659e-01, 2.868e-01,
        8.218e-02]])

In [29]:
y_test

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0])

In [31]:
clf=LogisticRegression(random_state=0)
clf.fit(X_train,y_train)

C:\Users\Acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [39]:
y_pred=clf.predict(X_test)

In [45]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0])

In [47]:
acc=accuracy_score(y_test,y_pred)
acc

0.956140350877193

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
data=pd.read_csv("C:/Users/Acer/Downloads/airlines_delay.csv")

In [51]:
data

Flight    Time  Length Airline AirportFrom AirportTo  DayOfWeek  Class
0       2313.0  1296.0   141.0      DL         ATL       HOU          1      0
1       6948.0   360.0   146.0      OO         COS       ORD          4      0
2       1247.0  1170.0   143.0      B6         BOS       CLT          3      0
3         31.0  1410.0   344.0      US         OGG       PHX          6      0
4        563.0   692.0    98.0      FL         BMI       ATL          4      0
...        ...     ...     ...     ...         ...       ...        ...    ...
539377  6973.0   530.0    72.0      OO         GEG       SEA          5      1
539378  1264.0   560.0   115.0      WN         LAS       DEN          4      1
539379  5209.0   827.0    74.0      EV         CAE       ATL          2      1
539380   607.0   715.0    65.0      WN         BWI       BUF          4      1
539381  6377.0   770.0    55.0      OO         CPR       DEN          2      1

[539382 rows x 8 columns]

In [53]:
label_encoder_Flight=LabelEncoder()
label_encoder_Time=LabelEncoder()
label_encoder_Length=LabelEncoder()
label_encoder_Airline=LabelEncoder()
label_encoder_AirportFrom=LabelEncoder()
label_encoder_AirportTo=LabelEncoder()
label_encoder_DayOfWeek=LabelEncoder()

In [55]:
data['Flight']=label_encoder_Flight.fit_transform(data['Flight'])
data['Flight']

0         2308
1         6198
2         1243
3           29
4          561
          ... 
539377    6223
539378    1260
539379    5004
539380     605
539381    5664
Name: Flight, Length: 539382, dtype: int64

In [57]:
data['Time']=label_encoder_Time.fit_transform(data['Time'])
data['Time']

0         1006
1           70
2          880
3         1112
4          402
          ... 
539377     240
539378     270
539379     537
539380     425
539381     480
Name: Time, Length: 539382, dtype: int64

In [59]:
data['Length']=label_encoder_Time.fit_transform(data['Length'])
data['Length']

0         119
1         124
2         121
3         322
4          76
         ... 
539377     50
539378     93
539379     52
539380     43
539381     33
Name: Length, Length: 539382, dtype: int64

In [61]:
data['Airline']=label_encoder_Time.fit_transform(data['Airline'])
data['Airline']

0          5
1         12
2          3
3         14
4          8
          ..
539377    12
539378    15
539379     6
539380    15
539381    12
Name: Airline, Length: 539382, dtype: int32

In [63]:
data['AirportFrom']=label_encoder_Time.fit_transform(data['AirportFrom'])
data['AirportFrom']

0          16
1          65
2          35
3         203
4          32
         ... 
539377    111
539378    153
539379     47
539380     45
539381     67
Name: AirportFrom, Length: 539382, dtype: int32

In [65]:
data['AirportTo']=label_encoder_Time.fit_transform(data['AirportTo'])
data['AirportTo']

0         129
1         208
2          60
3         217
4          16
         ... 
539377    252
539378     79
539379     16
539380     43
539381     79
Name: AirportTo, Length: 539382, dtype: int32

In [67]:
data['DayOfWeek']=label_encoder_Time.fit_transform(data['DayOfWeek'])
data['DayOfWeek']

0         0
1         3
2         2
3         5
4         3
         ..
539377    4
539378    3
539379    1
539380    3
539381    1
Name: DayOfWeek, Length: 539382, dtype: int64

In [69]:
x= data.drop('Class',axis=1).values
y = data['Class'].values

In [71]:
x

array([[2308, 1006,  119, ...,   16,  129,    0],
       [6198,   70,  124, ...,   65,  208,    3],
       [1243,  880,  121, ...,   35,   60,    2],
       ...,
       [5004,  537,   52, ...,   47,   16,    1],
       [ 605,  425,   43, ...,   45,   43,    3],
       [5664,  480,   33, ...,   67,   79,    1]], dtype=int64)

In [73]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [81]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=32)

In [ ]:
clf=LogisticRegression(random_state=0)
clf.fit(X_train,y_train)
